require conf/machine/include/radxa-zero-3.inc

# Original BSP default config name was wrong.s
UBOOT_MACHINE = "radxa-zero-3w-rk3566_defconfig"
KERNEL_DEVICETREE = "rockchip/rk3566-radxa-zero-3w.dtb"
WKS_FILE = "rockchip_ab.wks"

UBOOT_EXTLINUX_KERNEL_IMAGE = "/${KERNEL_IMAGETYPE}"
RK_IMAGE_INCLUDES_UBOOT_ENV = "yes"

# Define the two boot labels
UBOOT_EXTLINUX_LABELS = "slot-a slot-b"
UBOOT_EXTLINUX_DEFAULT_LABEL = "slot-a"
UBOOT_EXTLINUX_TIMEOUT = "30"
# Label A Configuration
UBOOT_EXTLINUX_MENU_DESCRIPTION:slot-a = "slot-a"
UBOOT_EXTLINUX_ROOT:slot-a = "root=PARTLABEL=rootfsA"
# Label B Configuration
UBOOT_EXTLINUX_MENU_DESCRIPTION:slot-b = "slot-b"
UBOOT_EXTLINUX_ROOT:slot-b = "root=PARTLABEL=rootfsB"

# Deploy fit image and extlinux files to boot partition.
IMAGE_BOOT_FILES = " \
    ${KERNEL_IMAGETYPE} \
    extlinux.conf;extlinux/extlinux.conf \
"

# Remove boot files from rootfs
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "u-boot-extlinux kernel-image fitImage kernel-devicetree"